baseurl = "http://rusnasonov.com/"
languageCode = "ru,en"
title = "rusnasonov"
theme = "hugo-rusnasonov-theme"
publishDir = "docs"
sectionPagesMenu = "main"

[params]
notoc = 1
avatar = "/images/avatar.jpg"
yandexMetrica = 46434456

