baseurl = "https://rusnasonov.com/"
languageCode = "ru,en"
title = "Ruslan Nasonov"
theme = "hugo-rusnasonov-theme"
publishDir = "output"
sectionPagesMenu = "main"
enableRobotsTXT = true

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsUseClassic = false

# See https://help.farbox.com/pygments.html
pygmentsStyle = "trac"

[params]
notoc = 1
description = "Блог об IT"
keywords = ["программирование", "блог", "it", "ит", "блог о программировании"]
author = "Ruslan Nasonov"
avatar = "/images/avatar.jpg"
yandexMetrica = 46434456
