baseurl = "https://rusnasonov.github.io/blog/"
languageCode = "ru,en"
title = "rusnasonov"
theme = "hyde"
publishDir = "docs"

[params]
  description = " "
  #googleAnalytics="UA-73974245-1"
  #yandexMetrica=35459907
  #disqusShortname= "rusnassonov"

#[[menu.main]]
#    name = "tools"
#    weight = 0
#    identifier = "tools"
#    url = "/tools/"

#[[menu.main]]
#    name = "books"
#    weight = 0
#    url = "/books/"
