baseurl = "http://rusnasonov.com/"
languageCode = "ru,en"
title = "rusnasonov"
theme = "hugo-rusnasonov-theme"
publishDir = "docs"
sectionPagesMenu = "main"
enableRobotsTXT = true

[params]
notoc = 1
description = "Блог об IT"
keywords = ["программирование", "блог", "it", "ит", "блог о программировании"]
author = "Руслан Насонов"
avatar = "/images/avatar.jpg"
yandexMetrica = 46434456

