version: '2'

services:
    remark42:
        image: umputun/remark42:latest
        restart: always
        container_name: "remark42"
        ports:
            - "443:8443"
            - "80:8080"
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"
        environment:
            - REMARK_URL=https://comments.rusnasonov.com
            - SITE=rusnasonov
            - SECRET=***
            - STORE_BOLT_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - AUTH_GITHUB_CID=***
            - AUTH_GITHUB_CSEC=***
            - AUTH_GOOGLE_CID=***
            - AUTH_GOOGLE_CSEC=***
            - SSL_TYPE=auto
            - SSL_ACME_EMAIL=rus.nasonov@gmail.com
            - ADMIN_SHARED_EMAIL=rus.nasonov@gmail.com
            - ADMIN_SHARED_ID=github_a4c601c38b235b53e98490e38c110b937d959588,google_a9194abead4f1196fb7d052ed012c9d235c27894
        volumes:
            - ./var:/srv/var