name: publish

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        push_branch: 'master'
        commit_message: 'publish'
    - name: build Gihub Pages
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
            github.repos.requestPageBuild({owner: 'rusnasonov', repo: 'blog'})

      
