name: publish

on:
    push:
        branches:
            - master

env:
    GO_VERSION: 1.18

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
              with:
                  ref: master
                  token: ${{ secrets.GH_TOKEN || github.token }}
            - name: build blog
              uses: github-actions-x/hugo@master
            - name: build server
              uses: actions/setup-go@v3
              with:
                  go-version: ${{ env.GO_VERSION }}
                  check-latest: true
            - run: cd server/ && go build -o blog . && cd ..

