# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "rusnasonov"
license = "MIT"
licenselink = "https://github.com/rusnasonov"
description = ""
homepage = "https://github.com/rusnasonov"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.36

[author]
  name = "Ruslan Nasonov"
  homepage = "https://github.com/rusnasonov"